{% set python_min = '3.10' %}
{% set name = "magicattr" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/frmdstryr/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5e59537cad483712274ab6dbddf7035fbcc01215c398a6a4ecd9e78a21a74c65

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - magicattr
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/frmdstryr/magicattr
  summary: magicattr
  description: |
    A getattr and setattr that works on nested objects, lists, dictionaries, and any combination thereof without resorting to eval.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mukhery
